### PR TITLE
Changes made according to request.

### PR DESCRIPTION
**Pull request by SahilDave04**
I renamed the files with some different names.
Check out "2nd.py", I think you don't need this file.

### CODE REVIEW

**Comment by minhaj-313** [comment]
@SahilDave04  Great, I appreciate it. Thanks for contributing.
Please Give ⭐and follow.

**Comment by SahilDave04** [comment]
Follow me too. 
If you find some exciting Open Source Projects please do forward them to me in the comments.

**Comment by minhaj-313** [comment]
@SahilDave04  Yeah off course.

If Possible checkout issues of this Repo

**Comment by SahilDave04** [comment]
This current repo?

**Comment by minhaj-313** [comment]
@SahilDave04  Yes

**Comment by SahilDave04** [comment]
Ohk let me see if I find something interesting

**Comment by minhaj-313** [comment]
> Ohk let me see if I find something interesting

Okay go ahead

**Pull request merged**
